kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: hello-openshift
  labels:
    app: hello-openshift
    app.kubernetes.io/component: hello-openshift
    app.kubernetes.io/instance: hello-openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: openshift/hello-openshift
      from:
        kind: DockerImage
        name: openshift/hello-openshift
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source