apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - constraintTemplate_service.yaml
  - constraint_service.yaml
  # From https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/requiredlabels
  - constraintTemplate_requiredLabel.yaml
  - constraint_requiredLabel.yaml